name: Make Release

on:
  push:
    branches: [117-*]

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - id: variables
        run: |
          set -x
          echo "::set-output name=version::`head -1 superfields/release-notes.md | cut -d' ' -f2`"
          echo "::set-output name=title::`head -1 superfields/release-notes.md | sed -n -e 's/^.* - //p'`"
          export NOTES=`cat superfields/release-notes.md | sed -e '0,/^# /d;/^# /,$d'`
          export NOTES="${NOTES//'%'/'%25'}"
          export NOTES="${NOTES//$'\n'/'%0A'}"
          export NOTES="${NOTES//$'\r'/'%0D'}""
          echo "::set-output name=notes::$NOTES"
      - id: test
        run: |
          echo "${{ steps.variables.outputs.version }}"
          echo "${{ steps.variables.outputs.title }}"
          echo "${{ steps.variables.outputs.notes }}"